[package]
name = "secret-borsh-storage"
version = "1.0.0"
authors = [
    "hoomp3",
]
edition = { workspace = true }
description = "Fork of cw-storage-plus using Borsh encoding."

[features]
default = []

[dependencies]
cosmwasm-std = { workspace = true }
serde = { workspace = true }
schemars = { workspace = true }
cw-storage-plus = { package = "secret-storage-plus", path = "../plus" }
borsh = { workspace = true }
borsh-derive = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
rstest_reuse = { workspace = true }
rand = { workspace = true }
criterion = { workspace = true }
