[package]
name = "query-authentication"
version = "0.1.0"
edition = { workspace = true }
authors = [ "Guy Garcia" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
remain = "0.2.2"
ripemd160 = "0.9.1"
secp256k1 = "0.27.0"
bech32 = "0.8.1"

sha2 = { version = "0.9.1", default-features = false }
