[package]
name = "shade-toolkit"
version = "0.1.0"
edition = { workspace = true }
authors = [ "hoomp3" ]
description = "Toolkit used by Shade Protocol contracts developed for Secret Network"

[features]
default = []
testing = ["shade-multi-test", "dep:anyhow"]

[dependencies]
cosmwasm-std = { workspace = true }
cosmwasm-schema = { workspace = true }
serde = { workspace = true }
borsh = { workspace = true }

secret-storage-plus = { path = "../storage/plus" }
better-secret-math = { path = "../math" }
anyhow = { workspace = true, optional = true }

[target.'cfg(not(target_arch="wasm32"))'.dependencies]
rstest = { workspace = true }
shade-multi-test = { path = "../multi-test", optional = true }
