[package]
name = "shade-multi-test"
version = "0.13.4"
authors = [
  "Ethan Frey <ethanfrey@users.noreply.github.com>",

  # Refactored for Secret Network
  "hoomp3",
]
edition = { workspace = true }
description = "Test helpers for multi-contract interactions"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["staking"]
iterator = ["cosmwasm-std/iterator"]
stargate = ["cosmwasm-std/stargate"]
staking = ["cosmwasm-std/staking"]
backtrace = ["anyhow/backtrace"]

[dependencies]
nanoid = { workspace = true }
cw-storage-plus = { package = "secret-storage-plus", path = "../../packages/storage/plus" }
cosmwasm-std = { workspace = true, features = ["staking", "stargate"] }
itertools = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
prost = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
derivative = { workspace = true }
